Repository nervosnetwork/neuron, pull requests merged in 2019-07, with the labels that each got.

#698 [ᚬmaster] Release v0.1.0 alpha.11
  lerna.json
  package.json
  packages/neuron-ui/.storybook/addons.js
  packages/neuron-ui/package.json
  packages/neuron-ui/src/components/History/hooks.ts
  packages/neuron-ui/src/components/History/index.tsx
  packages/neuron-ui/src/components/WalletWizard/index.tsx
  packages/neuron-ui/src/containers/Main/hooks.ts
  packages/neuron-ui/src/states/stateProvider/reducer.ts
  packages/neuron-ui/src/stories/Addresses.stories.tsx
  packages/neuron-ui/src/stories/GeneralSetting.stories.tsx
  packages/neuron-ui/src/stories/History.stories.tsx
  packages/neuron-ui/src/stories/Overview.stories.tsx
  packages/neuron-ui/src/stories/Receive.stories.tsx
  packages/neuron-ui/src/stories/SyncStatus.stories.tsx
  packages/neuron-ui/src/utils/formatters.test.ts
  packages/neuron-ui/src/utils/formatters.ts
  packages/neuron-wallet/package.json
  packages/neuron-wallet/src/listeners/address.ts
  packages/neuron-wallet/src/listeners/tx-status.ts
  packages/neuron-wallet/src/main.ts
  packages/neuron-wallet/src/services/sync/block-listener.ts
  packages/neuron-wallet/src/services/sync/queue.ts
  packages/neuron-wallet/src/startup/sync-block-task/task.ts
  yarn.lock
Labels: alpha

#724 [ᚬrc/v0.1.0-alpha.14] register necessary icons
  packages/neuron-ui/src/components/History/index.tsx
  packages/neuron-ui/src/components/TransactionList/index.tsx
Labels: hotfix

#752 refactor: Rename package names removing @nervosnetwork scope
  package.json
  packages/neuron-ui/package.json
  packages/neuron-wallet/package.json
Labels: m:infrastructure
