Repository nervosnetwork/neuron, pull requests merged in 2019-02, with the labels that each got.

#26 ESLint config
  .editorconfig
  .vscode/settings.json
  package.json
  packages/electron-app/package.json
  packages/electron-app/tsconfig.json
  packages/react-app/package.json
  packages/react-app/tsconfig.json
  yarn.lock
Labels: t:chore

#29 Test setup
  README.md
  package.json
  packages/react-app/package.json
Labels: t:test

#36 refactor: rename package names
  .vscode/launch.json
  .vscode/settings.json
  package.json
  packages/electron-app/electron-builder.yml
  packages/neuron-ui/.eslintrc.js
  packages/neuron-ui/config-overrides.js
  packages/neuron-ui/package.json
  packages/neuron-ui/public/favicon.ico
  packages/neuron-ui/public/index.html
  packages/neuron-ui/public/manifest.json
  packages/neuron-ui/src/components/App.test.tsx
  packages/neuron-ui/src/components/App.tsx
  packages/neuron-ui/src/components/Cells/index.tsx
  packages/neuron-ui/src/components/Header/index.tsx
  packages/neuron-ui/src/components/Network/index.tsx
  packages/neuron-ui/src/components/Notification/index.tsx
  packages/neuron-ui/src/components/Providers/index.tsx
  packages/neuron-ui/src/components/Sidebar/index.tsx
  packages/neuron-ui/src/components/Transfer/index.tsx
  packages/neuron-ui/src/contexts/chain.ts
  packages/neuron-ui/src/contexts/wallet.ts
  packages/neuron-ui/src/index.tsx
  packages/neuron-ui/src/logo.svg
  packages/neuron-ui/src/react-app-env.d.ts
  packages/neuron-ui/src/serviceWorker.ts
  packages/neuron-ui/src/setupTests.ts
  packages/neuron-ui/src/styles/index.scss
  packages/neuron-ui/src/styles/layout.scss
  packages/neuron-ui/src/utils/const.ts
  packages/neuron-ui/src/utils/ipc.ts
  packages/neuron-ui/tsconfig.json
  packages/neuron-wallet/assets/images/icon.icns
  packages/neuron-wallet/assets/images/icon.ico
  packages/neuron-wallet/electron-builder.yml
  packages/neuron-wallet/package.json
  packages/neuron-wallet/src/IPCChannel.ts
  packages/neuron-wallet/src/main.ts
  packages/neuron-wallet/src/mock.ts
  packages/neuron-wallet/src/utils/const.ts
  packages/neuron-wallet/tsconfig.json
  packages/react-app/src/react-app-env.d.ts
Labels: t:chore

#41 fix(ui): set BrowserWindow's title bar style to default
  packages/neuron-wallet/src/main.ts
Labels: t:bug

#40 chore(deps): update yarn.lock caused by recent deps change
  yarn.lock
Labels: t:chore

#64 Manage window properties/state
  packages/neuron-wallet/package.json
  packages/neuron-wallet/src/main.ts
Labels: m:infrastructure

#80 feat: add package naming conventions
  packages/neuron-wallet/electron-builder.yml
Labels: m:infrastructure

#98 refactor: wizard on if there is wallet in context
  packages/neuron-ui/src/components/Router/index.tsx
  packages/neuron-ui/src/components/WalletWizard/actionC.tsx
  packages/neuron-ui/src/components/WalletWizard/actionD.tsx
  packages/neuron-ui/src/components/WalletWizard/createWallet.tsx
  packages/neuron-ui/src/components/WalletWizard/importWallet.tsx
  packages/neuron-ui/src/components/WalletWizard/index.tsx
  packages/neuron-ui/src/containers/MainContent/index.tsx
  packages/neuron-ui/src/containers/Providers/index.tsx
  packages/neuron-ui/src/contexts/Settings.ts
  packages/neuron-ui/src/contexts/Wallet.ts
  packages/neuron-ui/src/widgets/FullScreenView.tsx
Labels: m:architecture

#101 Simplify and clean up tasks
  README.md
  package.json
  packages/neuron-ui/package.json
  packages/neuron-wallet/package.json
  packages/neuron-wallet/src/main.ts
Labels: m:infrastructure

#111 refactor: extract env and encapsulate isDevMode
  packages/neuron-wallet/src/env.ts
  packages/neuron-wallet/src/main.ts
  packages/neuron-wallet/src/menu.ts
Labels: t:enhancement
